apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ tpl .Values.configMap.configMapName . }}
data:
  QUERY_DEFAULTS_LIMIT: "25"
  AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
  PERSISTENCE_DATA_PATH: '{{ .Values.volume.containerPath }}'
  DEFAULT_VECTORIZER_MODULE: 'none'
  CLUSTER_HOSTNAME: 'node1'