apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ tpl .Values.deployment.containerName . }}
          image: {{ .Values.deployment.image }}
          imagePullPolicy: IfNotPresent
          ports:
            {{- range .Values.networking.ports }}
            - containerPort: {{ .containerPort }}
            {{- end }}
          args:
            - --host
            - 0.0.0.0
            - --port
            - '{{ (index .Values.networking.ports 0).containerPort }}'
            - --scheme
            - http
          envFrom:
            - configMapRef:
                name: {{ tpl .Values.configMap.configMapName . }}
          env:
            {{- range .Values.secrets }}
            - name: {{ .envName }}
              valueFrom:
                secretKeyRef:
                  name: {{ .secretName }}
                  key: {{ .secretKey }}
            {{- end }}
          volumeMounts:
            - mountPath: {{ .Values.volume.containerPath }}
              name: {{ tpl .Values.volume.volumeName . }}
      volumes:
        - name: {{ tpl .Values.volume.volumeName . }}
          persistentVolumeClaim:
            claimName: {{ tpl .Values.volume.pvcName . }}
