apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: {{ .Values.deployment.image }}
          imagePullPolicy: IfNotPresent
          ports:
            {{- range .Values.networking.ports }}
            - containerPort: {{ .containerPort }}
            {{- end }}
          args:
            - --host
            - 0.0.0.0
            - --port
            - '{{ (index .Values.networking.ports 0).containerPort }}'
            - --scheme
            - http
          envFrom:
            - configMapRef:
                name: {{ tpl .Values.configMap.configMapName . }}
