{{- range .Values.secrets }}
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ tpl .secretName . }}
  namespace: infra-prod
spec:
  itemPath: {{ .onepasswordItemPath }}
{{- end}}

