{{- range $index, $element := .Values.secrets }}
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ tpl $element.secretName $ }}
  namespace: infra-prod
spec:
  itemPath: {{ $element.onepasswordItemPath }}
{{- end}}

