apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ tpl .Values.volume.pvcName . }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: craig-hostpath
  resources:
    requests:
      storage: 100Gi