apiVersion: v1
kind: Service
metadata:
  name: {{ tpl .Values.networking.serviceName . }}
spec:
  type: NodePort
  selector:
    app: {{ tpl .Values.appName . }}
  ports:
    {{- range $index, $element := .Values.networking.ports }}
    - port: {{ $element.containerPort }}
      targetPort: {{ $element.containerPort }}
      nodePort: {{ $element.nodePort }}
      name: "port-{{ $index }}"
    {{- end}}