apiVersion: v1
kind: Service
metadata:
  name: {{ tpl .Values.networking.serviceName . }}
spec:
  type: ClusterIP
  selector:
    app: {{ tpl .Values.appName }}
  ports:
    {{- range .Values.networking.ports }}
    - port: {{ .containerPort }}
      targetPort: {{ .containerPort }}
    {{- end}}