apiVersion: v1
kind: Service
metadata:
  name: {{ tpl .Values.networking.serviceName . }}
spec:
  type: NodePort
  selector:
    app: {{ tpl .Values.appName }}
  ports:
    {{- range .Values.networking.ports }}
    - port: {{ .containerPort }}
      targetPort: {{ .containerPort }}
      nodePort: {{ .nodePort }}
    {{- end}}